// Name generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"rest-gin-gorm/exercise"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitExerciseAPI(db *gorm.DB) exercise.ExerciseAPI {
	exerciseRepository := exercise.ProvideExerciseRepostiory(db)
	exerciseService := exercise.ProvideExerciseService(exerciseRepository)
	exerciseAPI := exercise.ProvideExerciseAPI(exerciseService)
	return exerciseAPI
}
