// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"github.com/letkemanpete78/gymman/exercise"
)

import (
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

// Injectors from wire.go:

func InitAPI(db *gorm.DB) exercise.API {
	repository := exercise.ProvideExerciseRepostiory(db)
	service := exercise.ProvideService(repository)
	api := exercise.ProvideAPI(service)
	return api
}
